[package]
name = "Project"
version = "0.1.0"
authors = ["EnginTekin <tekin.engin@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rand = "0.7.3"
clap = "3.0.0-beta.1"